## this composefile uses the latest prebuild image from https://github.com/1-011-c/testbefund-api/packages
version: '3.1'
services:
  testbefund-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password # password will have to be the same as DB_PASS
    volumes:
      - testbefund-db-data:/var/lib/postgresql/data
  testbefund-api:
    image: docker.pkg.github.com/1-011-c/testbefund-api/testbefund-api:master
    environment:
      DB_URL: jdbc:postgresql://testbefund-db:5432/postgres
      DB_USER: postgres
      DB_PASS: password
      APP_USER: secretUser
      APP_PASS: verySecretPass
      DB_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - 8080:8080
volumes:
  testbefund-db-data: {}

