apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testbefund
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbefund
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: testbefund
    spec:
      containers:
      - name: api
        image: testbefund/api:master
        ports:
        - containerPort: 8080
        env:
        - name: DB_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
        - name: DB_PASS
          value: postgresql
        - name: DB_URL
          value: jdbc:postgresql://sqldb:5432/testbefund
        - name: DB_USER
          value: postgresql
        - name: APP_USER
          value: testbefund
        - name: APP_PASSWORD
          value: testbefund
      restartPolicy: Always
status: {}
