name: build

on:
  push:
    branches:
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate API
      run: ./gradlew -q openApiGenerate
    - name: Build with gradle
      run: ./gradlew -q bootJar
    - uses: nelonoel/branch-name@v1
    - name: Build & Push to Docker Hub
      uses: zenato/docker-action@v1.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        repository: testbefund/api
        tag: ${{env.BRANCH_NAME}}
